In [13]:
!pip install mlxtend

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: mlxtend in c:\users\admin\appdata\roaming\python\python39\site-packages (0.23.4)
Requirement already satisfied: matplotlib>=3.0.0 in c:\programdata\anaconda3\lib\site-packages (from mlxtend) (3.5.1)
Requirement already satisfied: scikit-learn>=1.3.1 in c:\users\admin\appdata\roaming\python\python39\site-packages (from mlxtend) (1.6.1)
Requirement already satisfied: numpy>=1.16.2 in c:\users\admin\appdata\roaming\python\python39\site-packages (from mlxtend) (1.26.4)
Requirement already satisfied: pandas>=0.24.2 in c:\programdata\anaconda3\lib\site-packages (from mlxtend) (1.4.2)
Requirement already satisfied: joblib>=0.13.2 in c:\users\admin\appdata\roaming\python\python39\site-packages (from mlxtend) (1.5.3)
Requirement already satisfied: scipy>=1.2.1 in c:\users\admin\appdata\roaming\python\python39\site-packages (from mlxtend) (1.13.1)
Requirement already satisfied: packaging>=20.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (21.3)
Requirement already satisfied: pillow>=6.2.0 in c:\users\admin\appdata\roaming\python\python39\site-packages (from matplotlib>=3.0.0->mlxtend) (9.5.0)
Requirement already satisfied: cycler>=0.10 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (4.25.0)
Requirement already satisfied: pyparsing>=2.2.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (3.0.4)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2021.3)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.16.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\admin\appdata\roaming\python\python39\site-packages (from scikit-learn>=1.3.1->mlxtend) (3.6.0)

In [14]:

# Importing necessary libraries
import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules

# Sample transaction dataset
dataset = [
    ['Milk', 'Bread', 'Butter'],
    ['Milk', 'Diaper', 'Juice', 'Bread'],
    ['Milk', 'Diaper', 'Bread'],
    ['Diaper', 'Juice', 'Bread'],
    ['Milk', 'Diaper', 'Juice', 'Bread']
]

# Extract all items
all_items = set()
for transaction in dataset:
    for item in transaction:
        if item not in all_items:
            all_items.add(item)

print("All items:", all_items)

All items: {'Bread', 'Milk', 'Butter', 'Juice', 'Diaper'}

In [15]:
# One Hot Encoding the transactions and converting to Pandas DataFrame
transaction_list = []

for transaction in dataset:
    transaction_dict = {}

    for item in all_items:
        transaction_dict[item] = item in transaction

    transaction_list.append(transaction_dict)

df = pd.DataFrame(transaction_list)

df

   Bread   Milk  Butter  Juice  Diaper
0   True   True    True  False   False
1   True   True   False   True    True
2   True   True   False  False    True
3   True  False   False   True    True
4   True   True   False   True    True

In [16]:
frequent_itemsets = apriori(df, min_support=0.6, use_colnames=True)

print("Frequent Itemsets:")
frequent_itemsets

Frequent Itemsets:

    support                itemsets
0       1.0                 (Bread)
1       0.8                  (Milk)
2       0.6                 (Juice)
3       0.8                (Diaper)
4       0.8           (Milk, Bread)
5       0.6          (Juice, Bread)
6       0.8         (Diaper, Bread)
7       0.6          (Diaper, Milk)
8       0.6         (Juice, Diaper)
9       0.6   (Diaper, Milk, Bread)
10      0.6  (Juice, Diaper, Bread)

In [17]:
rules = association_rules(
    frequent_itemsets,
    metric="confidence",
    min_threshold=0.7,
    num_itemsets=2
)

print("Association Rules:")
rules

Association Rules:

C:\Users\admin\AppData\Roaming\Python\Python39\site-packages\mlxtend\frequent_patterns\association_rules.py:186: RuntimeWarning: invalid value encountered in divide
  cert_metric = np.where(certainty_denom == 0, 0, certainty_num / certainty_denom)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Milk),(Bread),0.8,1.0,0.8,1.00,1.0000,1.0,0.00,inf,0.00,0.80,0.000,0.900
1,(Bread),(Milk),1.0,0.8,0.8,0.80,1.0000,1.0,0.00,1.0,0.00,0.80,0.000,0.900
2,(Juice),(Bread),0.6,1.0,0.6,1.00,1.0000,1.0,0.00,inf,0.00,0.60,0.000,0.800
3,(Diaper),(Bread),0.8,1.0,0.8,1.00,1.0000,1.0,0.00,inf,0.00,0.80,0.000,0.900
4,(Bread),(Diaper),1.0,0.8,0.8,0.80,1.0000,1.0,0.00,1.0,0.00,0.80,0.000,0.900
5,(Diaper),(Milk),0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.60,-0.250,0.750
6,(Milk),(Diaper),0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.60,-0.250,0.750
7,(Juice),(Diaper),0.6,0.8,0.6,1.00,1.2500,1.0,0.12,inf,0.50,0.75,1.000,0.875
8,(Diaper),(Juice),0.8,0.6,0.6,0.75,1.2500,1.0,0.12,1.6,1.00,0.75,0.375,0.875
9,"(Diaper, Milk)",(Bread),0.6,1.0,0.6,1.00,1.0000,1.0,0.00,inf,0.00,0.60,0.000,0.800
10,"(Diaper, Bread)",(Milk),0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.60,-0.250,0.750
11,"(Milk, Bread)",(Diaper),0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.60,-0.250,0.750
12,(Diaper),"(Milk, Bread)",0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.60,-0.250,0.750
13,(Milk),"(Diaper, Bread)",0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.60,-0.250,0.750
14,"(Juice, Diaper)",(Bread),0.6,1.0,0.6,1.00,1.0000,1.0,0.00,inf,0.00,0.60,0.000,0.800
15,"(Juice, Bread)",(Diaper),0.6,0.8,0.6,1.00,1.2500,1.0,0.12,inf,0.50,0.75,1.000,0.875
16,"(Diaper, Bread)",(Juice),0.8,0.6,0.6,0.75,1.2500,1.0,0.12,1.6,1.00,0.75,0.375,0.875
17,(Juice),"(Diaper, Bread)",0.6,0.8,0.6,1.00,1.2500,1.0,0.12,inf,0.50,0.75,1.000,0.875
18,(Diaper),"(Juice, Bread)",0.8,0.6,0.6,0.75,1.2500,1.0,0.12,1.6,1.00,0.75,0.375,0.875

In [18]:
strong_rules = rules[
    (rules['confidence'] > 0.7) & (rules['lift'] > 1)
]

print("Strong Association Rules (Confidence > 0.7 and Lift > 1):")
strong_rules.head()

Strong Association Rules (Confidence > 0.7 and Lift > 1):

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
7,(Juice),(Diaper),0.6,0.8,0.6,1.00,1.25,1.0,0.12,inf,0.5,0.75,1.000,0.875
8,(Diaper),(Juice),0.8,0.6,0.6,0.75,1.25,1.0,0.12,1.6,1.0,0.75,0.375,0.875
15,"(Juice, Bread)",(Diaper),0.6,0.8,0.6,1.00,1.25,1.0,0.12,inf,0.5,0.75,1.000,0.875
16,"(Diaper, Bread)",(Juice),0.8,0.6,0.6,0.75,1.25,1.0,0.12,1.6,1.0,0.75,0.375,0.875
17,(Juice),"(Diaper, Bread)",0.6,0.8,0.6,1.00,1.25,1.0,0.12,inf,0.5,0.75,1.000,0.875